language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: w1DWMKp6XqCQ70pujirOpmic+GZOm8G1fwcwt2SIg0s950s9OZ+fquVxcCj5+HE5YdtORQIWeVY2o86TK52V584IK559T8xcSqP2hFXYW/hT/RnZhJySKvqDZElvnSwt0aktlxeQFVWhsRfn8fgDC3MwHk++c4E8PzSBBAAjPoBCuB9CO7ezWzlN9iQLDfusrc+pHr+rGZOVzSvjI77Rtyhmn1KgBDZR4ibIpVTeL1beBkFyVVeLBCwpXdyDVZbjYaPU3jPhOKhMsOyXEJSjxmO13LGAuFSfQzIoAnlChMb+q8n/ObNTLlHarJuPrO6pJ/iR22aNpTMBJotb1kjinvZKXLljZuZMNTVMRjbSsw4DfjyjGz4Nmz8Ke82JiTMe76AD2CmaF/KtLkVZo/O5DGZf4rovRdho9ewJrS7s/M2xAoStsE0tfKyMJVO/E/ee8hVNyKacr1k+4Sw2/KX1LaReJGw5q3RtURoXJerR/xXGrRHNXiVnqacbWcjuYFGRZNN5DWM3VfP3JKeBoCntmMuWXX6dnWvv6S41LlfHHzvfPowU8i7nKHglpbaK7z77TYTBZP8pMfHDIl3Ik+TAUcKv/XfSUnUkPwQFfBTaiKCaw+KXravbIy4Vdrh5YNju7bR6eV+eS40NVsegzzRyF2IIX/DIIIoy9gfqFOubms4=
